title: Bootstrap Reason React App
tagline: From Zero to Release in a blink 🚀
tags:
  - reason
  - bucklescript
  - reason-react
  - react
description:
  Hello and welcome!

  In this lab we will cover the basic setup needed to build Reason React
  applications, covering testing, documenting them, building, and releasing them!
template:
  name: my-reason-react-app
  repo: lab-template.bootstrap-reason-react-app
before:
  - type: createIssue
    title: Welcome
    body: 00.00-welcome.md
    comments:
      - 00.01-what-we-are-building.md
      - 00.02-begin-here.md

steps:

- title: Welcome
  description: Get the course started!
  event: issues
  link: '{{ repoUrl }}/issues/1'
  actions:
  - type: gate
    left: '%payload.action%'
    operator: ===
    right: closed
  - type: createPullRequest
    title: Getting Started
    body: 01.00-setup.md
    head: setup
    action_id: setup_pr
  - type: respond
    issue: '%actions.setup_pr.data.number%'
    with: 01.00-setup.activities.md
    data:
      repo_clone_url: '%actions.setup_pr.data.repository.ssh_url%'
  - type: assignRegistrant
    issue: '%actions.setup_pr.data.number%'
  - type: respond
    with: 00.03-goto-first-pr.md
    data:
      url: '%actions.setup_pr.data.html_url%'

- title: 'Install Dependencies'
  description: Get the repo up and working in your computer
  event: pull_request.synchronize
  link: '%actions.setup_pr.data.html_url%'
  actions:
  - type: getFileContents
    action_id: fileContents
    filename: 'yarn.lock'
  - type: gate
    left: '/^# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.$/gm'
    operator: test
    right: '%actions.fileContents%'
  - type: respond
    with: 01.01-install-vs-code.md

- title: 'Setting up an Editor'
  description: Install VS Code
  event: pull_request.synchronize
  link: '%actions.setup_pr.data.html_url%'
  actions:
  - type: getFileContents
    action_id: fileContents
    filename: lib/js/src/model.bs.js
  - type: gate
    left: '/Generated by BUCKLESCRIPT/gm'
    operator: test
    right: '%actions.fileContents%'
  - type: respond
    with: 01.02-build-project.md

- title: 'Building the Project'
  description: Create project bundle
  event: pull_request.synchronize
  link: '%actions.setup_pr.data.html_url%'
  actions:
  - type: getFileContents
    filename: bundle/index.js
    action_id: bundle_index_js
  - type: gate
    left: '/fastpack/gm'
    operator: test
    right: '%actions.bundle_index_js%'
  - type: respond
    with: 01.03-run-tests.md

- title: 'Testing the Project'
  description: Run the tests in the project.
  event: pull_request.synchronize
  link: '%actions.setup_pr.data.html_url%'
  actions:
  - type: getFileContents
    filename: __tests__/model_test.re
    action_id: model_test_re
  - type: gate
    left: '/toBe\(true\)/gm'
    operator: test
    right: '%actions.model_test_re%'
  - type: respond
    with: 01.05-check-app-local.md

- title: 'Verifying the App Works'
  description: Create project bundle
  event: pull_request_review.submitted
  link: '%actions.setup_pr.data.html_url%'
  actions:
  - type: gate
    left: '%payload.review.state%'
    operator: ===
    right: approved
  - type: createIssue
    title: This is just the Beginning!
    body: 02.00-end.md
    action_id: final_issue
  - type: respond
    with: 01.06-github-pages.md
    data:
      final_issue: '%actions.final_issue.data.html_url%'
  - type: mergePullRequest
    pullRequest: Getting Started
  - type: deleteBranch
    branch: setup

- title: 'Fin: Wrapping it up!'
  description: Additional links
  event: issues
  link: '%actions.final_issue.data.html_url%'
  actions:
  - type: gate
    left: '%payload.action%'
    operator: ===
    right: closed
