title: Intro to Reason
tagline: Learn You Some Reason for Great Good by building your first Reason React App!
description: Longer explanation of the same; Reason Reason Reason Reason
template:
  name: reason-todo-app
  repo: lab.template-intro-to-reason
before:
  - type: createIssue
    title: Welcome
    body: 00.00-welcome.md
    comments:
      - 00.01-what-we-are-building.md
      - 00.02-begin-here.md

steps:
- title: Welcome
  description: Confirm that the course should begin.
  event: issues
  link: '{{ repoUrl }}/issues/1'
  actions:
  - type: gate
    left: '%payload.action%'
    operator: ===
    right: closed
  - type: createPullRequest
    title: Getting Started
    body: 01.00-setup.md
    head: setup
    action_id: setup_pr
  - type: assignRegistrant
    issue: '%actions.setup_pr.data.number%'
  - type: respond
    with: 00.03-goto-first-pr.md
    data:
      url: '%actions.setup_pr.data.html_url%'
