title: Intro to Reason
tagline: Get Started with ReasonML
description: Longer explanation of the same; Reason Reason Reason Reason
template:
  name: reason-todo-app
  repo: lab.template-intro-to-reason
before:
  - type: createPullRequest
    title: Welcome
    body: 000-welcome.md
    head: update-version
    data:
      url: 'https://codesandbox.io/s/github/ostera/learn-you-some-reason/tree/update-version'
    action_id: first_pr_id

steps:
- title: Create a package.json
  description: Initialize your project by creating a package.json
  event: pull_request
  link: '{{ repoUrl }}/pull/1'
  actions:
  - type: getFileContents
    action_id: packageJsonContents
    filename: 'package.json'
  - type: gate
    left: '/"version": ".+",?/gm'
    operator: test
    right: '%actions.packageJsonContents%'
    else:
    - type: respond
      with: no-version.md
  - type: respond
    with: you-succeeded.md
