title: Learn You Some Reason
tagline: Learn how to write some Reason for Great Good
description: Longer explanation of the same; Reason Reason Reason Reason
template:
  name: learn-you-some-reason
  repo: lab-learn-you-some-reason-template
before:
  - type: createPullRequest
    title: Welcome
    body: 000-welcome.md
    head: package-json
    action_id: first_pr_id

steps:
- title: Create a package.json
  description: Initialize your project by creating a package.json
  event: pull_request.synchronize
  link: '{{ repoUrl }}/pull/1'
  actions:
  - type: getFileContents
    action_id: packageJsonContents
    filename: 'package.json'
  - type: gate
    left: '/"version": ".+",?/gm'
    operator: test
    right: '%actions.packageJsonContents%'
    else:
    - type: respond
      with: no-version.md
      issue: 1
  - type: respond
    with: you-succeeded.md
    issue: 1
